// System Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const VERIFY_START = 'VERIFY_START';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const RESEND_TOKEN_START = 'RESEND_TOKEN_START';
export const RESEND_TOKEN_FAIL = 'RESEND_TOKEN_FAIL';
export const RESEND_TOKEN_SUCCESS = 'RESEND_TOKEN_SUCCESS';
export const RESET_AUTH_FLAGS = 'RESET_AUTH_FLAGS';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
