// System Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const VERIFY_START = 'VERIFY_START';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const RESEND_TOKEN_START = 'RESEND_TOKEN_START';
export const RESEND_TOKEN_FAIL = 'RESEND_TOKEN_FAIL';
export const RESEND_TOKEN_SUCCESS = 'RESEND_TOKEN_SUCCESS';
export const SET_FORGOT_PASSWORD_STATUS = 'SET_FORGOT_PASSWORD_STATUS';
export const SET_RESET_PASSWORD_STATUS = 'SET_RESET_PASSWORD_STATUS';
export const RESET_AUTH_FLAGS = 'RESET_AUTH_FLAGS';
export const GET_USER_DETAILS_START = 'GET_USER_DETAILS_START';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';
export const SAVE_USER_DATA_START = 'SAVE_USER_DATA_START';
export const SAVE_USER_DATA_SUCCESS = 'SAVE_USER_DATA_SUCCESS';
export const SAVE_USER_DATA_FAIL = 'SAVE_USER_DATA_FAIL';

// Knowledge
export const CREATE_KNOWLEDGE_START = 'CREATE_KNOWLEDGE_START';
export const CREATE_KNOWLEDGE_SUCCESS = 'CREATE_KNOWLEDGE_SUCCESS';
export const CREATE_KNOWLEDGE_FAIL = 'CREATE_KNOWLEDGE_FAIL';
